# Generated by Django 3.0.4 on 2020-04-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0033_submittedplace_donation_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='bounds',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='place',
            name='geom',
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='radius',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
