# Generated by Django 3.0.4 on 2020-04-11 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0034_auto_20200411_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='place',
            name='lng',
        ),
    ]
